### PR TITLE
Highlighting fixes

### PR DESCRIPTION
**Pull request by hyprbst**
There was some wonky highlighting in a bunch of the articles.

This should clean that right up :smile:

### CODE REVIEW

**Comment by swat30** [comment]
@hyprbst can you send along a screenshot of an example of the change? Tks!

**Comment by hyprbst** [comment]
# Boot from volume before

screenshot_2015-11-11_13-41-34

# boot from volume after

screenshot_2015-11-11_13-42-36

---

# container keys before

screenshot_2015-11-11_13-44-29

# container keys after

screenshot_2015-11-11_13-44-10

**Comment by swat30** [comment]
:+1:

**Comment by thurloat** [comment]
Awesome fix, looks much more consistent.

**Pull request merged**
